# Generated by Django 6.0.6 on 2026-06-22 04:56

import datetime
import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswork', models.BooleanField(default=True, verbose_name='click here if it works')),
                ('name', models.CharField(default='sujan', max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('message', models.TextField(blank=True)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('stock', models.BigIntegerField()),
                ('stock_1', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('file', models.FileField(upload_to='files')),
                ('dob', models.DateField(default=datetime.datetime(2026, 6, 22, 4, 56, 39, 680818))),
                ('date_field', models.DateTimeField(default=datetime.datetime(2026, 6, 22, 4, 56, 39, 680827))),
                ('creat_at', models.DateField(auto_now_add=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=20, null=True)),
                ('subject', multiselectfield.db.fields.MultiSelectField(choices=[('django', 'django'), ('python', 'python')], max_length=13, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='NP')),
                ('product_key', models.UUIDField(default=uuid.UUID('2339f040-0378-40f9-ab97-5c257c8f49ff'), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('cpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvtApp.city')),
                ('interest', models.ManyToManyField(to='mvtApp.interest')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='profile/')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvtApp.person')),
            ],
        ),
    ]
