# Generated by Django 6.0.6 on 2026-06-23 04:45

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvtApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_field',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 4, 45, 51, 982073)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2026, 6, 23, 4, 45, 51, 982064)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='product_key',
            field=models.UUIDField(default=uuid.UUID('a6c26986-2f2e-4305-83ae-a215850e0d8a'), editable=False),
        ),
    ]
