# Generated by Django 6.0.6 on 2026-06-19 04:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvtApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswork', models.BooleanField(default=True, verbose_name='clic here if it works')),
                ('name', models.CharField(default='sujan', max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('message', models.TextField(blank=True)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('stock', models.BigIntegerField()),
                ('stock_1', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('file', models.FileField(upload_to='files')),
                ('dob', models.DateField(default=datetime.datetime(2026, 6, 19, 4, 42, 8, 494675))),
                ('date_field', models.DateTimeField(default=datetime.datetime(2026, 6, 19, 4, 42, 8, 494684))),
                ('creat_at', models.DateField(auto_now_add=True, null=True)),
                ('update_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
