# Generated by Django 6.0.6 on 2026-06-19 05:22

import datetime
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvtApp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='NP'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('django', 'django'), ('python', 'python')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_field',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 19, 5, 22, 13, 298952)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2026, 6, 19, 5, 22, 13, 298943)),
        ),
    ]
