# Generated by Django 6.0.6 on 2026-06-21 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvtApp', '0003_contact_gender_contact_phone_contact_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('cpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_field',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 2, 27, 26, 667624)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2026, 6, 21, 2, 27, 26, 667616)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='iswork',
            field=models.BooleanField(default=True, verbose_name='click here if it works'),
        ),
    ]
